/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.qualificationdata.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.qualificationdata.MyRuntimeModule;
import org.xtext.example.qualificationdata.MyStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyIdeSetup extends MyStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyRuntimeModule(), new MyIdeModule()));
	}
	
}
