/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.qualificationdata.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.qualificationdata.ui.internal.QualificationdataActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(QualificationdataActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		QualificationdataActivator activator = QualificationdataActivator.getInstance();
		return activator != null ? activator.getInjector(QualificationdataActivator.ORG_XTEXT_EXAMPLE_QUALIFICATIONDATA_MY) : null;
	}

}
